Enable-magisk-update = true
parallel-jobs = 1
# --- TAMBAHAN BARU DI SINI ---
rv-brand = "Extended"
# -----------------------------

# --- YOUTUBE (Versi Ringan & Aktif) ---
[YouTube]
build-mode = "module"
# Fitur yang DIBUANG agar ringan (sesuai request Anda sebelumnya):
excluded-patches = "'Shorts', 'Create button', 'Cast button', 'Wide Searchbar', 'Switch create button with notifications button', 'Return YouTube Dislike'"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# --- YOUTUBE MUSIC (Versi Ringan & Aktif) ---
[Music]
build-mode = "module"
arch = "both"
excluded-patches = "'Upgrade button', 'Cast button', 'Taste building', 'Get premium'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

# --- BAGIAN BAWAH INI BIARKAN 'FALSE' (MATI) ---
[GooglePhotos]
enabled = false
# ... (dan seterusnya biarkan false)

[YouTube-Extended]
enabled = false
# ... (biarkan false karena kita sudah pakai rv-brand di paling atas)
